In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,f1_score, precision_score, recall_score

In [2]:
df_sentiment = pd.read_csv('sentiment_reduced.csv')
df_sentiment = df_sentiment.drop(columns='Unnamed: 0')
df_sentiment

Sentiment  0  1  2  3  4  5  6  7  8  ...  989  990  991  992  993  994  \
0             0  1  1  0  1  0  0  1  1  1  ...    0    0    0    0    0    0   
1             0  1  1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
2             0  0  1  1  1  0  0  0  0  1  ...    0    0    0    0    0    0   
3             0  1  1  1  1  0  0  0  0  0  ...    0    0    0    0    0    0   
4             0  1  1  0  1  1  0  1  0  0  ...    0    0    0    0    0    0   
...         ... .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...   
2995          1  0  1  1  0  0  1  0  1  0  ...    0    0    0    0    0    0   
2996          0  0  0  0  1  1  0  1  0  0  ...    1    0    0    0    0    0   
2997          1  1  1  0  1  1  0  0  1  0  ...    0    0    0    0    0    0   
2998          0  1  0  1  0  0  1  1  0  0  ...    0    0    0    0    0    0   
2999          1  1  0  1  1  1  1  1  1  1  ...    0    0    0    0    0    0   

      995  996  997  998  
0       0    0    0    1  
1       0    0    0    0  
2       0    0    0    0  
3       0    0    0    0  
4       0    0    0    0  
...   ...  ...  ...  ...  
2995    0    0    0    0  
2996    0    0    0    0  
2997    0    0    0    0  
2998    0    0    0    0  
2999    0    0    0    0  

[3000 rows x 1000 columns]

In [3]:
X = df_sentiment.drop(['Sentiment'], axis = 1)
y = df_sentiment['Sentiment']

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 26)

In [5]:
x_train.shape, x_test.shape

((2400, 999), (600, 999))

In [6]:
from sklearn.linear_model import LogisticRegression

# Create instance of model
lreg = LogisticRegression()
# Pass training data into model
lreg.fit(x_train, y_train)

LogisticRegression()

In [7]:
y_pred_lreg = lreg.predict(x_test)

In [8]:
# Confusion Matrix
print('Logistic Regression')
print('\n')
print('Confusion Matrix')
print(confusion_matrix(y_test, y_pred_lreg))
print('--'*50)

# Classification Report
print('Classification Report')
print(classification_report(y_test,y_pred_lreg))


# Accuracy of our model
print('--'*50)
logreg_accuracy = round(accuracy_score(y_test, y_pred_lreg) * 100,8)
print('Accuracy = ', logreg_accuracy,'%')

Logistic Regression


Confusion Matrix
[[210  73]
 [ 72 245]]
----------------------------------------------------------------------------------------------------
Classification Report
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       283
           1       0.77      0.77      0.77       317

    accuracy                           0.76       600
   macro avg       0.76      0.76      0.76       600
weighted avg       0.76      0.76      0.76       600

----------------------------------------------------------------------------------------------------
Accuracy =  75.83333333 %


In [18]:
#########
#########


In [9]:
df_rating = pd.read_csv('rating_reduced.csv')
df_rating = df_rating.drop(columns='Unnamed: 0')
df_rating

Rating  0  1  2  3  4  5  6  7  8  ...  989  990  991  992  993  994  \
0          2  1  1  0  0  0  0  1  0  0  ...    0    0    0    1    0    0   
1          4  0  1  0  1  1  0  1  0  0  ...    0    0    0    0    0    0   
2          2  1  1  1  1  0  1  1  0  0  ...    0    0    0    0    0    0   
3          4  1  1  1  1  1  0  1  1  0  ...    0    0    0    0    0    0   
4          4  0  1  0  0  1  0  1  1  0  ...    0    0    0    0    0    0   
...      ... .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...   
2995       4  1  0  0  1  1  0  1  1  0  ...    0    0    0    0    0    0   
2996       4  1  1  1  0  1  1  1  0  1  ...    0    0    0    0    0    0   
2997       4  1  1  1  0  0  0  0  1  0  ...    0    0    0    0    0    0   
2998       3  1  1  1  1  1  1  0  1  0  ...    0    0    0    0    0    0   
2999       4  1  0  1  1  1  1  0  1  1  ...    0    0    0    0    0    0   

      995  996  997  998  
0       0    0    0    0  
1       0    0    0    0  
2       0    0    0    0  
3       0    0    0    0  
4       0    0    0    0  
...   ...  ...  ...  ...  
2995    0    0    0    0  
2996    0    0    0    0  
2997    0    0    0    0  
2998    0    0    0    0  
2999    0    0    0    0  

[3000 rows x 1000 columns]

In [10]:
X = df_rating.drop(['Rating'], axis = 1)
y = df_rating['Rating']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 26)

In [12]:
from sklearn.linear_model import LogisticRegression

# Create instance of model
lreg = LogisticRegression()
# Pass training data into model
lreg.fit(x_train, y_train)

C:\Users\valfaro\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred_lreg = lreg.predict(x_test)

In [14]:
# Confusion Matrix
print('Logistic Regression')
print('\n')
print('Confusion Matrix')
print(confusion_matrix(y_test, y_pred_lreg))
print('--'*50)

# Classification Report
print('Classification Report')
print(classification_report(y_test,y_pred_lreg))


# Accuracy of our model
print('--'*50)
logreg_accuracy = round(accuracy_score(y_test, y_pred_lreg) * 100,8)
print('Accuracy = ', logreg_accuracy,'%')

Logistic Regression


Confusion Matrix
[[ 39  18   8   3]
 [ 20  28  27  17]
 [  2  25  40  61]
 [  5  12  46 249]]
----------------------------------------------------------------------------------------------------
Classification Report
              precision    recall  f1-score   support

           1       0.59      0.57      0.58        68
           2       0.34      0.30      0.32        92
           3       0.33      0.31      0.32       128
           4       0.75      0.80      0.78       312

    accuracy                           0.59       600
   macro avg       0.50      0.50      0.50       600
weighted avg       0.58      0.59      0.59       600

----------------------------------------------------------------------------------------------------
Accuracy =  59.33333333 %


In [15]:
#everything runs nice!